### ISSUE TITLE
Elasticsearch Reports 503 Service Unavailable

### ISSUE THREAD

**Issue by Jaraxal** [datarank/tempest#9] opened 2015-07-13 14:09 UTC
I have a 6 node cluster running ES 1.5.2.  All 6 nodes are data nodes with 3 nodes set up to be allowed as masters.  When I installed the tempest plugin and restarted ES, all of the nodes would respond with 503 curl calls.  I tried restarted each of the nodes, but the problem didn't resolve itself.  I was forced to uninstall the plugin.  After a uninstalling the plugin and restarting the nodes, all 6 came up without any issues.

Because of my environment, I can't copy and past logs.  I'll provide what I can by manually copying the seemingly relevant parts.

While the plugin was installed, the elected master node (host4) had the following in the logs:
[2015-07-09 18:08:05,260] [INFO] [com.datarank.tempest.allocator.LocalMinimumShardsAllocator]  [host4] Unable to allocate [<index_name>] [5] [p], ignoring.

The above line repeats for all of the indexes, then I see:
[2015-07-09 18:08:05,281] [INFO] [com.datarank.tempest.allocator.LocalMinimumShardsAllocator]  [host4] Exiting allocateUnassigned, 0 unassigned shards and 650 ignored unassigned shards remaining.
[2015-07-09 18:08:05,282] [INFO] [com.datarank.tempest.allocator.LocalMinimumShardsAllocator]  [host4] Rebalancing.
[2015-07-09 18:08:05,282] [INFO] [com.datarank.tempest.allocator.LocalMinimumShardsAllocator]  [host4] 0 unassigned shards and 650 ignored unassigned shards remain, exiting rebalance.

I later see the following (which is repeated for every index):
[2015-07-09 18:08:17,956] [ERROR] [discovery.zen               ]  [host4] unexpected failure during [zen-disco-join (elected_as_master)] Index [<index_name>]: Shard [2] routing table has wrong number of replicas, expected [1], got [2].

If there are specific log messages you would like me to look for, let me know and I will provide more information.  Unfortunately I am not able to provide the logs in their entirety.

**Comment by sawyercade** [comment] 2015-07-14 14:51
Giving this a look today - I suspect it's versioning related, and if so we'll create a branch for 1.5.2. Just in case though, could you post your ES settings file?

**Comment by Jaraxal** [comment] 2015-07-14 15:29
elasticsearch.yml (removed commented info for brevity):
cluster.name: mycluster

node.name: "host01"

# master servers have node.master: true set properly
node.master: false
node.data: true

# I have 2 zones configured, zone1 and zone2
node.rack: zone1

index.number_of_shards: 12

index.number_of_replicas: 1

path.data: /grid/disk06/elasticsearch/data,/grid/disk07/elasticsearch/data

plugin.mandatory: analysis-phonetic,mapper-attachments

transport.tcp.compress: true

indices.recovery.max_bytes_per_sec: 400mb

discovery.zen.minimum_master_nodes: 2

discovery.zen.ping.unicast.hosts: ["host04","host05","host06"]

script.disable_dynamic: false

# added for kibana
http.cors.enabled: true
http.cors.allow-orgin: http://host01:9200

# added for tempest
cluster.routing.allocation.type: com.datarank.tempest.allocator.LocalMinimumShardsAllocator

And here is the output of GET /_cluster/settings (routing settings were part of an effort to adjust the default routing):

{
  "persistent" : {
    "indices" : {
      "recovery" : {
        "max_bytes_per_sec" : "400mb"
      }
    },
    "cluster" : {
      "routing" : {
        "allocation" : {
          "enable" : "all",
          "balance" : {
            "index" : "0.95f",
            "primary" : "0.95f",
            "shard" : "0.95f"
          }
        }
      }
    },
    "discovery" : {
      "zen" : {
        "minimum_master_nodes" : "3",
        "publish_timeout" : "1m"
      }
    }
  },
  "transient" : { }
}

**Comment by sawyercade** [comment] 2015-07-14 20:25
Here's what's happening: tempest is building a model and then attempting to move shards in your ES cluster to match the model, right? However, ES (specifically the AllocationDeciders) is saying that the modeled moves aren't valid on your cluster. There are a number of reasons that this can happen, but I strongly suspect in your case that it has something to do with [index-level routing settings](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/index-modules-allocation.html).

Have you set any index-level routing settings? Possibly corresponding to your zones? I know prior to tempest, pretty much the only way to balance a cluster of heterogeneously-sized indexes was to use index.routing.allocation and cluster.routing.allocation settings to attempt to spread larger indices evenly across the cluster (which in some use cases can require continuous cluster monitoring and tweaking, as you might know). However, tempest doesn't consider these settings when building a model (#2), since they're mostly used as a hacky way to do what tempest does anyways.

If you remove index-level allocation and awareness filtering, I suspect tempest will do its thing beautifully. If you're working within a production environment and have multiple indexes, you might want to take a [snapshot](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/modules-snapshots.html#_repositories) first so you don't have to go back in and restore those settings if you want to continue using the default ES balancer.

If the problem isn't the index-level allocation settings, we can debug ES's AllocationDeciders and see why it's not letting tempest allocate shards where it wants within your cluster.

**Comment by Jaraxal** [comment] 2015-07-14 20:37
Thanks for the reply.  I am not using index-level allocation, only the cluster routing allocation shown above.

**Comment by sawyercade** [comment] 2015-07-14 21:15
Well I'll be darned! I've created [a branch with some extra debug info](https://github.com/datarank/tempest/tree/9-allocation-deciders) that should help us figure out why ES is preventing allocation. There's a zip in the top level if you're not using maven to build locally.

Look for messages like the following:
[2015-07-14 16:01:10,158][INFO ][com.datarank.tempest.allocator.LocalMinimumShardsAllocator] [charybdis_node_0] Unable to allocate [index_0][0][p]: [YES(shard is not allocated to same node or host)][NO(node does not match index include filters [tag:"someTagNoNodeHas"])][YES(shard is primary)][YES(below primary recovery limit of [4])][YES(all allocations are allowed)][YES(all allocation is enabled)][YES(no allocation awareness enabled)][YES(total shard limit disabled: [-1] <= 0)][YES(primary shard can be allocated anywhere)][YES(enough disk for shard on node, free: [361.4gb])][YES(no snapshots are currently running)]ignoring.

The "NO" with explanation is what we're really interested in.

**Comment by Jaraxal** [comment] 2015-07-16 19:47
I will try to test this as soon as I can.  Unfortunately, I will be out on vacation until the 27th.  I will give the debug version a test when I get back.  I've already downloaded it.

**Comment by gnuhpc** [comment] 2015-08-19 12:45
I also encountered this situation after intalling this plugin in my 4node es(1.6) cluster.

**Comment by sawyercade** [comment] 2015-08-20 14:28
@gnuhpc If you'd like to give the debug version I posted above a shot and post your master node's logs here, that'll give us the information we need to debug the problem and figure out what's keeping ES from allowing the allocations.

**Comment by Jaraxal** [comment] 2015-08-20 15:26
I still have this as a todo item as well.  I've just been busy.  I hope to test this in the next week or so.

**Comment by cmoad** [comment] 2015-09-15 14:18
I added tempest to our QA cluster yesterday and all seemed to work well, but I am getting this error below when it's trying to allocate today's index (we have daily indices obviously). We have 1 replica enabled and shards have EC2 availability zone restrictions. This didn't seem to cause an issue yesterday when rebalancing the cluster. I believe I also saw the issue below when trying to uninstall the plugin, so I might be stuck. Still working on that. Thanks.

```
[2015-09-15 13:55:02,782][DEBUG][action.admin.indices.create] [search-master02.qa1.us-east-1.local] [global.y2015m09d15.v3] failed to create
org.elasticsearch.cluster.routing.RoutingValidationException: [Index [global.y2015m09d15.v3]: Shard [0] routing table has wrong number of replicas, expected [1], got [2], Index [global.y2015m09d15.v3]: Shard [1] routing table has wrong number of replicas, expected [1], got [2], Index [global.y2015m09d15.v3]: Shard [2] routing table has wrong number of replicas, expected [1], got [2]]
        at org.elasticsearch.cluster.routing.RoutingTable.validateRaiseException(RoutingTable.java:98)
        at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:165)
        at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:148)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:469)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by sawyercade** [comment] 2015-09-15 19:23
Thanks @cmoad, I'm looking into it now. I suspect it's caused by a disconnect between ES's allocation restrictions and tempest's modeled allocation restrictions. If that's the case, your issue might be fixed when #14 is fixed (tempest will simply continue attempting to find valid allocation destinations for unassigned shards). Will fix as soon as possible.

**Comment by cerelisa** [comment] 2016-03-08 19:38
Hi

I'm seeing the same errors described here with the shard routine table:
   Shard [3] routing table has wrong number of replicas, expected [1], got [2]

I am using ES v1.7.1 with Tempest 1.0.0.  Any updates on a fix for this issue?

Thanks!

**Comment by aewhite** [comment] 2016-06-04 14:26
This is fixed in Tempest 2.x

**Closed by aewhite** 2016-06-04 14:26 UTC
Labels: bug
